// Code generated by MockRepository. DO NOT EDIT.
package mock

import (
	"context"

	"github.com/1solomonwakhungu/go-production-api-starter/internal/model"
)

// MockUserRepository is a hand-written mock implementation of repository.UserRepository.
// It records calls and returns configurable responses for table-driven tests.
type MockUserRepository struct {
	CreateFunc  func(ctx context.Context, user *model.User) error
	GetByIDFunc func(ctx context.Context, id string) (*model.User, error)
	GetAllFunc  func(ctx context.Context, limit, offset int) ([]*model.User, error)
	UpdateFunc  func(ctx context.Context, user *model.User) error
	DeleteFunc  func(ctx context.Context, id string) error

	// Call recording
	CreateCalls  []CreateCall
	GetByIDCalls []GetByIDCall
	GetAllCalls  []GetAllCall
	UpdateCalls  []UpdateCall
	DeleteCalls  []DeleteCall
}

type CreateCall struct {
	Ctx  context.Context
	User *model.User
}

type GetByIDCall struct {
	Ctx context.Context
	ID  string
}

type GetAllCall struct {
	Ctx    context.Context
	Limit  int
	Offset int
}

type UpdateCall struct {
	Ctx  context.Context
	User *model.User
}

type DeleteCall struct {
	Ctx context.Context
	ID  string
}

func (m *MockUserRepository) Create(ctx context.Context, user *model.User) error {
	m.CreateCalls = append(m.CreateCalls, CreateCall{Ctx: ctx, User: user})
	if m.CreateFunc != nil {
		return m.CreateFunc(ctx, user)
	}
	return nil
}

func (m *MockUserRepository) GetByID(ctx context.Context, id string) (*model.User, error) {
	m.GetByIDCalls = append(m.GetByIDCalls, GetByIDCall{Ctx: ctx, ID: id})
	if m.GetByIDFunc != nil {
		return m.GetByIDFunc(ctx, id)
	}
	return nil, nil
}

func (m *MockUserRepository) GetAll(ctx context.Context, limit, offset int) ([]*model.User, error) {
	m.GetAllCalls = append(m.GetAllCalls, GetAllCall{Ctx: ctx, Limit: limit, Offset: offset})
	if m.GetAllFunc != nil {
		return m.GetAllFunc(ctx, limit, offset)
	}
	return nil, nil
}

func (m *MockUserRepository) Update(ctx context.Context, user *model.User) error {
	m.UpdateCalls = append(m.UpdateCalls, UpdateCall{Ctx: ctx, User: user})
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, user)
	}
	return nil
}

func (m *MockUserRepository) Delete(ctx context.Context, id string) error {
	m.DeleteCalls = append(m.DeleteCalls, DeleteCall{Ctx: ctx, ID: id})
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ctx, id)
	}
	return nil
}
